apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: azure-asdf
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: azure-asdf 
  name: azure-asdf
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: azure-asdf 
